### ISSUE TITLE
ZSnoW grabs mouse inputs

### ISSUE THREAD

**Issue by galitus** [DarkVanityOfLight/znow#8]
Hey,

I got an error while building it:

`install
+- install zsnow
   +- zig build-exe zsnow ReleaseSafe native
      +- run zig-wayland-scanner (wayland.zig)
         +- zig build-exe zig-wayland-scanner Debug native 1 errors
/home/user/.cache/zig/p/wayland-0.4.0-lQa1khbMAQAsLS2eBR7M5lofyEGPIbu2iFDmoz8lPC27/src/scanner.zig:31:49: error: struct 'array_list.ArrayListAligned([]const u8,null)' has no member named 'empty'
    var protocols: std.ArrayList([]const u8) = .empty;
                                               ~^~~~~
/usr/lib64/zig/0.14.1/lib/std/array_list.zig:31:12: note: struct declared here
    return struct {
           ^~~~~~
referenced by:
    posixCallMainAndExit: /usr/lib64/zig/0.14.1/lib/std/start.zig:660:37
    _start: /usr/lib64/zig/0.14.1/lib/std/start.zig:468:40
    3 reference(s) hidden; use '-freference-trace=5' to see all references
error: the following command failed with 1 compilation errors:
/usr/lib64/zig/0.14.1/bin/zig build-exe -Mroot=/home/user/.cache/zig/p/wayland-0.4.0-lQa1khbMAQAsLS2eBR7M5lofyEGPIbu2iFDmoz8lPC27/src/scanner.zig --cache-dir /tmp/ZSnoW/.zig-cache --global-cache-dir /home/user/.cache/zig --name zig-wayland-scanner --zig-lib-dir /usr/lib64/zig/0.14.1/lib/ --listen=- 
Build Summary: 0/5 steps succeeded; 1 failed
install transitive failure
+- install zsnow transitive failure
   +- zig build-exe zsnow ReleaseSafe native transitive failure
      +- run zig-wayland-scanner (wayland.zig) transitive failure
         +- zig build-exe zig-wayland-scanner Debug native 1 errors
error: the following build command failed with exit code 1:
/tmp/ZSnoW/.zig-cache/o/ba0887c39201bca1dc62dc7a515dcb6f/build /usr/lib64/zig/0.14.1/bin/zig /usr/lib64/zig/0.14.1/lib /tmp/ZSnoW /tmp/ZSnoW/.zig-cache /home/user/.cache/zig --seed 0xe188ea3d -Zb07a40eac92b0893 -Doptimize=ReleaseSafe
`

Installed versions
zig: 0.14.1
wayland-protocols: 1.45
wlr-protocols:   1.0_p20220608

do you need more? how can I provide it?

Thanks

**Comment by DarkVanityOfLight** [comment]
This probably happens because of your zig version. The build currently uses zig 0.15.2. If you go back to 7256e498a74177d8633da99901b450b03965ae41 this commit it might work with 0.14.1

**Comment by galitus** [comment]
Sorry, for the late response.
I had to update my system first (gentoo)
Yeah, the newer version fixed it.

But is it correct that the snow is falling only on the desktop/wallpaper and behind every window?
And not infront of every non-fullscreen window?
Because it is not an application on the taskbar, I cannot even set it to above everything else.
Should I open another issue for that problem?

**Comment by DarkVanityOfLight** [comment]
It is supposed to be like that but you can change it afaik.

**Comment by DarkVanityOfLight** [comment]
In main.zig line 223:
`const layer_surface: *zwlr.LayerSurfaceV1 = try layer_shell.getLayerSurface(surface, output.output, zwlr.LayerShellV1.Layer.background, "waysnow");`

You can change the `zwlr.LayerShellV1.Layer.background`  to any of these:

- background
- bottom
- top
- overlay

However I do not know how this will interact with fullscreen applications, and/or keyboard and mouse passthroughs to the windows.

**Comment by galitus** [comment]
Hey, thanks for the quick response.
overlay would be nice, but mouse is unusable then, because every click seems to go to zsnow on the overlay layer.
top also worked on top of windows, but mouse isn't even visible anymore
bottom the same as using top.

So, yeah none of this works.
I haven't tested fullscreen.

**Comment by DarkVanityOfLight** [comment]
You can try the following.
Below the 
```    
const layer_surface: *zwlr.LayerSurfaceV1 = try layer_shell.getLayerSurface(surface, output.output, zwlr.LayerShellV1.Layer.background, "waysnow");
layer_surface.setSize(output.pWidth, output.pHeight);
```
You can try to set the keyboard interavtivity to none, as described [here](https://wayland.app/protocols/wlr-layer-shell-unstable-v1#zwlr_layer_surface_v1:request:set_keyboard_interactivity)
This should work something like this, though I m not sure about the details:
`layer_surface.setKeyBoardInteractivity(.none)`
Or set to something close to `zwlr.LayerSurfaceV1.KeyboardInteractivity.none`

If this works feel free to open a pull request. If not I can take a look later today.

**Comment by DarkVanityOfLight** [comment]
Sadly I don't think there is a good way to perform mouse pass-through on wayland :(

**Comment by galitus** [comment]
the keyboard worked just fine, only the mouse couldn't interact with everything on the screen because the
snow layer was above everything else and was receiving the input from the mouse

because of this, I just tested with the background setting, no desktop icon is clickable, because the snow layer is above 
the desktop 

so, even this setting is less ideal

I just wanted to have something like xsnow just for wayland.

**Comment by DarkVanityOfLight** [comment]
Hey, the input grabbing should be fixed now.
To have the snow display over windows but not over fullscreen windows try setting the layer to top. If you want to even put it above fullscreen put it on overlay.
:3

**Comment by galitus** [comment]
Very nice. It just works. 
Nothing to complain.
So, you only get a big THANK YOU.
